{
  "openapi": "3.0.3",
  "info": {
    "title": "New Spec - OpenAPI 3.0",
    "description": "This is a sample description about this spec.",
    "termsOfService": "",
    "contact": {
      "email": ""
    },
    "license": {
      "name": "Apache 2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
    },
    "version": "1.0.0"
  },
  "externalDocs": {
    "description": "Find out more about spec",
    "url": ""
  },
  "servers": [
    {
      "url": "https://console.flecs.tech",
      "description": ""
    }
  ],
  "tags": [
    {
      "name": "Manifests",
      "description": ""
    }
  ],
  "paths": {
    "/api/v2/manifests/{app}/{version}": {
      "parameters": [],
      "get": {
        "description": "",
        "meta": {
          "element": "",
          "originalPath": "https://console.flecs.tech/api/v2/manifests/{app}/{version}"
        },
        "operationId": "get-api-v2-manifests-app-version",
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "required": true,
            "schema": {
              "type": "string",
              "pattern": "Bearer .+"
            }
          },
          {
            "name": "X-Session-Id",
            "in": "header",
            "required": true,
            "schema": {
              "type": "string",
              "pattern": "^[0-9a-f]{8}(?:-[0-9a-f]{4}){3}-[0-9a-f]{12}$"
            }
          },
          {
            "name": "app",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "version",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "https://raw.githubusercontent.com/FLECS-Technologies/app-sdk/main/manifest.schema.json"
                }
              }
            },
            "description": "App Manifests for App {app} in version {version}"
          },
          "403": {
            "content": {
              "application/json": {
                "examples": {
                  "example-0001": {
                    "value": {
                      "reason": "Missing Header: Authorization",
                      "statusCode": 403,
                      "statusText": "Forbidden"
                    }
                  }
                },
                "schema": {
                  "type": "object",
                  "properties": {
                    "reason": {
                      "type": "string"
                    },
                    "statusCode": {
                      "type": "integer"
                    },
                    "statusText": {
                      "type": "string"
                    }
                  }
                }
              }
            },
            "description": ""
          },
          "404": {
            "content": {
              "application/json": {
                "examples": {
                  "example-0001": {
                    "value": {
                      "statusCode": 404,
                      "statusText": "Not found"
                    }
                  }
                },
                "schema": {
                  "type": "object",
                  "properties": {
                    "statusCode": {
                      "type": "integer"
                    },
                    "statusText": {
                      "type": "string"
                    }
                  }
                }
              }
            },
            "description": "No such App/version combination"
          },
          "500": {
            "content": {
              "application/json": {
                "examples": {
                  "example-0001": {
                    "value": {
                      "reason": "Could not validate device activation",
                      "statusCode": 500,
                      "statusText": "Internal Server Error"
                    }
                  }
                },
                "schema": {
                  "type": "object",
                  "properties": {
                    "reason": {
                      "type": "string"
                    },
                    "statusCode": {
                      "type": "integer"
                    },
                    "statusText": {
                      "type": "string"
                    }
                  }
                }
              }
            },
            "description": ""
          }
        },
        "summary": "Download App manifest"
      }
    }
  },
  "components": {
    "schemas": {},
    "securitySchemes": {}
  }
}