{
  "openapi": "3.0.3",
  "info": {
    "title": "New Spec - OpenAPI 3.0",
    "description": "This is a sample description about this spec.",
    "termsOfService": "",
    "contact": {
      "email": ""
    },
    "license": {
      "name": "Apache 2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
    },
    "version": "1.0.0"
  },
  "externalDocs": {
    "description": "Find out more about spec",
    "url": ""
  },
  "servers": [
    {
      "url": "https://console.flecs.tech",
      "description": ""
    }
  ],
  "tags": [
    {
      "name": "Device",
      "description": ""
    }
  ],
  "paths": {
    "/api/v2/device/license/activate": {
      "parameters": [],
      "post": {
        "description": "",
        "meta": {
          "element": "",
          "originalPath": "https://console.flecs.tech/api/v2/device/license/activate"
        },
        "operationId": "post-api-v2-device-license-activate",
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "required": true,
            "schema": {
              "type": "string",
              "pattern": "Bearer .+"
            }
          },
          {
            "name": "X-Session-Id",
            "in": "header",
            "required": true,
            "schema": {
              "type": "string",
              "pattern": "^[0-9a-f]{8}(?:-[0-9a-f]{4}){3}-[0-9a-f]{12}$"
            }
          }
        ],
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "examples": {
                  "example-0001": {
                    "value": {
                      "data": {
                        "sessionId": "00000000-0000-0000-0000-000000000000"
                      },
                      "statusCode": 200,
                      "statusText": "OK"
                    }
                  }
                },
                "schema": {
                  "type": "object",
                  "properties": {
                    "data": {
                      "type": "object",
                      "properties": {
                        "sessionId": {
                          "type": "string",
                          "pattern": "^[0-9a-f]{8}(?:-[0-9a-f]{4}){3}-[0-9a-f]{12}$"
                        }
                      }
                    },
                    "statusCode": {
                      "type": "integer"
                    },
                    "statusText": {
                      "type": "string"
                    }
                  }
                }
              }
            },
            "description": "Device successfully activated"
          },
          "204": {
            "description": "Device already active"
          },
          "403": {
            "content": {
              "application/json": {
                "examples": {
                  "example-0001": {
                    "value": {
                      "reason": "Missing Header: Authorization",
                      "statusCode": 403,
                      "statusText": "Forbidden"
                    }
                  }
                },
                "schema": {
                  "type": "object",
                  "properties": {
                    "reason": {
                      "type": "string"
                    },
                    "statusCode": {
                      "type": "integer"
                    },
                    "statusText": {
                      "type": "string"
                    }
                  }
                }
              }
            },
            "description": ""
          },
          "500": {
            "content": {
              "application/json": {
                "examples": {
                  "example-0001": {
                    "value": {
                      "reason": "Could not validate device activation",
                      "statusCode": 500,
                      "statusText": "Internal Server Error"
                    }
                  }
                },
                "schema": {
                  "type": "object",
                  "properties": {
                    "reason": {
                      "type": "string"
                    },
                    "statusCode": {
                      "type": "integer"
                    },
                    "statusText": {
                      "type": "string"
                    }
                  }
                }
              }
            },
            "description": ""
          }
        },
        "summary": "Activate license",
        "tags": [
          "Device"
        ]
      }
    }
  },
  "components": {
    "schemas": {},
    "securitySchemes": {}
  }
}